name: GitHub Actions Ansible-lint
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: [main]
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: install python3 and python3-pip
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
      - name: install ansible-lint and yamllint
        run: |
          pip install ansible-lint
          pip install --user yamllint
      - name: run yamllint
        run: |
          yamllint  *.yaml    
      - name: run ansible-lint
        run: |
          ansible-lint  *.yaml              
